CREATE TABLE doctors (
    id SERIAL PRIMARY KEY,
    doc_name TEXT,
    content TEXT,
    suburb TEXT,
    category TEXT,
    sub_category TEXT,
    phone TEXT,
    lat TEXT,
    lng TEXT,
    address TEXT,
    u18 BOOLEAN,
    o18 BOOLEAN,
    u25 BOOLEAN,
    low_cost_ndis_option BOOLEAN,
    gp_ref_required BOOLEAN
);

INSERT INTO doctors(doc_name, content, suburb, category, sub_category, phone, lat, lng, address, u18, o18, u25, low_cost_ndis_option, gp_ref_required) VALUES
('Cary Nayda', 'As written by Cary Nayda:  I work extensively with members of the LGBTQIA+ community and have a strong professional interest in this space. I am a part of the queer community and seek to provide services that are accessible for all genders and sexual orientations  - GP referral may be required - Open to youth under 25', 'Mt Barker', 'Allied Health', '', '493437978', -35.0683877, 138.8578012, '26 Hack Street, Mount Barker South Australia, Australia', false, false, false, false, true),
('Dr Paula Stacey-Thomas', '<span>At The Chiropractic Domain, we have a diverse generational health practice and we welcome range of people from various ages and stages of life. We aim to create a safe place where people of diverse culture , sexual orientation, genders and abilities can attend. Chiropractic care can be provided to people who identify as gender diverse or gender neutral, as long as we understand how they would like to be identified.</span>  &nbsp;  Open to Under 18  Open to Over 18  Open to Youth under 25  Family space', 'Goodwood', 'Allied Health', '', '08 8272 4555', -34.9501, 138.5896682, 'The Chiropractic Domain, Goodwood Road, Goodwood SA, Australia', true, true, false, false, false),
('Tania Savelli', '', 'Norwood', 'Allied Health', '', '', -34.9150712, 138.6380068, 'Vocal Hub Collective, Magill Road, Norwood SA, Australia', false, false, false, false, false),
('Katrina Ryan', '', 'Norwood', 'Allied Health', '', '', -34.9150712, 138.6380068, 'Vocal Hub Collective, Magill Road, Norwood SA, Australia', false, false, false, false, false),
('Mack Madahar', 'Mr. Madahar Bio  I am a Nurse Practitioner with experience in treating and managing gender diverse individuals. I have worked with a number of specialist at RAH, Modbury hospital and other private specialist services. I respect all gender diverse population and respect and acknowledge their emotional wellbeing.  - Open to under 18 patients - Open to over 18 patients - Open to Youth Under 25 - Can continue Gender Affirming Hormone Therapy but does not initiate GAHT', 'Port Adelaide', 'Nurse Practitioner', 'Nurse Practitioner', '', -34.8519657, 138.5082122, 'Trinity Medical Centre, 28 College St, Port Adelaide SA 5015, Australia', false, false, true, false, false),
('James Aspinall', '- GP referral may be required', 'Fullarton', 'Gynaecology and Urology', 'Urologist', '8338 0370', -34.9508052, 138.6320468, '1 Florence Street, Fullarton SA, Australia', false, false, false, false, true),
('Professor Martin Oehler', '- GP referral may be required', 'Burnside', 'Gynaecology and Urology', 'Gynaecologist & Gynaecological Oncologist', '8202 7222', 0, 0, 'Burnside Hospital', false, false, false, false, true),
('Dr Fariba Behnia-Willison', '- Feminine Space - GP referral may be required', 'Ashford', 'Gynaecology and Urology', 'Gynaecologist', '8297 2822', 0, 0, 'FBW Gynaecology Plus', false, false, false, false, true),
('Dr Charlotte Paull', '- Feminine Space - GP referral may be required', 'Ashford', 'Gynaecology and Urology', 'Gynaecologist', '(08) 7082 3788', 0, 0, '2/41 Anzac Highway', false, false, false, false, true),
('Dr Nicola Denton', '- Feminine Space - GP referral may be required', 'North Adelaide', 'Gynaecology and Urology', 'Gynaecologist', '1300 604 377', 0, 0, 'Connery House', false, false, false, false, true),
('Dr Jane Woolcock', '- Feminine Space - GP referral may be required', 'North Adelaide', 'Gynaecology and Urology', 'Gynaecologist', '1300 604 377', 0, 0, 'Connery House', false, false, false, false, true),
('Dr Paul Knight', '- GP referral may be required', 'Kent Town', 'Gynaecology and Urology', 'Gynaecologist', '8132 0566', 0, 0, 'Advanced Gynaecological Surgery Centre', false, false, false, false, true),
('Reproductive and Endocrine Clinic', '- GP referral may be required - Low/no/NDIS cost options', 'Adelaide', 'Gynaecology and Urology', '', '8161 7592', 0, 0, 'Royal Adelaide Hospital', false, false, false, true, true),
('Dr Aimee Wiltshire', '- Feminine Space - GP referral may be required - Low/no/NDIS cost options', 'Adelaide', 'Gynaecology and Urology', 'Gynaecologist', ' 8161 7592', 0, 0, 'Women''s & Children''s Hospital', false, false, false, true, true),
('Dr Aimee Wiltshire', '- Feminine Space - GP referral may be required', 'North Adelaide', 'Gynaecology and Urology', 'Gynaecologist', '1300 604 377', 0, 0, 'Connery House', false, false, false, false, true),
('Dr Kylie Webber', '- Feminine Space - GP referral may be required - Low/no/NDIS cost options', 'Adelaide', 'Gynaecology and Urology', 'Gynaecologist', '8161 7592', 0, 0, 'Women''s & Children''s Hospital', false, false, false, true, true),
('Dr Kylie Webber', '- Feminine Space - GP referral may be required', 'North Adelaide', 'Gynaecology and Urology', 'Gynaecologist', '1300 604 377', 0, 0, '', false, false, false, false, true),
('Dr Anna Limgenco', '- Gender Affirming Hormone Therapy - Feminine Space', 'Elizabeth Vale', 'Gynaecology and Urology', 'Gynaecologist', '8282 5371', 0, 0, 'Calvary Central Districts Hospital', false, false, false, false, false),
('Dr Martin Ritossa', '- GP referral may be required', 'Kent Town', 'Gynaecology and Urology', 'Gynaecologist', '8132-0566', -34.92865642, 138.5999107, '', false, false, false, false, true),
('Dr Rebecca Nelson', '- GP referral always required - Under 18', 'North Adelaide', 'Paediatrics', 'Paediatrician', '08 7002 0140', -34.9097014, 138.6022375, 'Priority Paediatrics, 280 Melbourne St, North Adelaide SA 5006, Australia', true, false, false, false, false),
('Dr James Katsaros', '- GP referral may be required', 'North Adelaide', 'Surgical - Transmasculine', 'Chest (Top) Surgery ', '8239 0115', 0, 0, 'Northern Adelaide Day Surgery', false, false, false, false, true),
('Dr James Katsaros', '- GP referral may be required', 'North Adelaide', 'Surgical - Transmasculine', 'Chest (Top) Surgery ', '8239 0115', 0, 0, 'Northern Adelaide Day Surgery', false, false, false, false, true),
('Dr Quoc Lam', '- GP referral may be required', 'Adelaide', 'Surgical - Transmasculine', 'Chest (Top) Surgery ', '7070 0596', -34.92865642, 138.5999107, 'Cranford House Plastic Surgery', false, false, false, false, true),
('Dr Tony Moore', '- GP referral may be required', 'Stirling', 'Surgical - Transmasculine', 'Chest (Top) Surgery ', ' 7089 4486', -34.92865642, 138.5999107, 'Stirling Hospital', false, false, false, false, true),
('Dr Quoc Lam', '- GP referral may be required', 'Adelaide', 'Surgical - Transmasculine', 'Chest (Top) Surgery ', '7070 0596', -34.92865642, 138.5999107, 'Cranford House Plastic Surgery', false, false, false, false, true),
('Dr Damien Riggs', '- Under 18 - Family', 'Clarence Park', 'Allied Health', 'Clinical Psychotherapist ', '7122 4559', -34.92865642, 138.5999107, '', true, false, false, false, false),
('Lyn Sutton', 'On leave - Low/no/NDIS cost options - Youth under 25', 'Onkaparinga', 'Allied Health', 'Social Worker ', '1300 794 584', -35.1395311, 138.4713849, 'headspace Onkaparinga, Esplanade, Christies Beach SA, Australia', false, false, false, true, false),
('Lyn Sutton', 'On leave - Under 18 - Over 18 - Family - Low/no/NDIS cost options - Not taking new patients', 'Woodville', 'Allied Health', 'Social Worker ', '1300 794 584', -34.8793673, 138.5367483, 'SHINE SA - Woodville, Woodville Road, Woodville South SA, Australia', true, true, false, true, false),
('Zac Cannell', 'Trans Man - Youth under 25 - Low/no/NDIS cost options', 'Elizabeth', 'Allied Health', 'Social Worker', '1300 794 584', -34.92865642, 138.5999107, 'Metro Youth Health', false, false, false, true, false),
('Zac Cannell', 'Trans Man - Under 18 - Over 18 - Family - Low/no/NDIS cost options', 'Woodville', 'Allied Health', 'Social Worker ', '1300 794 584', -34.92865642, 138.5999107, 'SHINE SA Woodville', true, true, false, true, false),
('Sarah Ayling', '- Low/no/NDIS cost options - Youth under 25', 'Elizabeth', 'Allied Health', 'Social Worker', '8255 3477', -34.92865642, 138.5999107, 'Metro Youth Health', false, false, false, true, false),
('Anisa Varasteh', '', 'North Adelaide', 'Allied Health', 'Clinical Sexologist', '8361 7866', -34.9096938, 138.6031476, 'Relate Sexology, Melbourne Street, North Adelaide SA, Australia', false, false, false, false, false),
('Simone Miller', '', 'Ceduna', 'Allied Health', 'Social & Emotional Wellbeing Worker', '8626 2500', -34.92865642, 138.5999107, '1 Eyre Highway', false, false, false, false, false),
('Layla Assad-Salha', '- Low/no/NDIS cost options - Over 18 - Youth under 25 - GP referral may be required', 'Marion', 'Allied Health', 'headspace Centre Coordinator and Mental Health Clinician', '8490 7700', -35.0180589, 138.5503035, 'headspace Marion, Kaurna Country, Sturt Road, Marion SA, Australia', false, true, false, true, true),
('Donna Carley', '- Low/no/NDIS cost options - Youth under 25', 'Elizabeth', 'Allied Health', 'Social Worker ', '8255 3477', -34.92865642, 138.5999107, 'Metro Youth Health', false, false, false, true, false),
('Zan Maeder', '- Low/no/NDIS cost options', 'Adelaide', 'Allied Health', 'Queer Counsellor', '0401 820 217', -34.92865642, 138.5999107, 'RAD Counselling', false, false, false, true, false),
('Dr Stephanie Russell', 'Trans woman - Under 18 - Over 18', 'Teringie', 'Allied Health', 'Counsellor and Psychotherapist', '7079 4324', -34.92865642, 138.5999107, 'Adelaide Hills Inclusive Counselling', true, true, false, false, false),
('Jesse Muller', 'Offers Online Services (they/them) Gender Diverse Person - Under 18 - Over 18 - Family - Low/no/NDIS cost options - Youth under 25', 'Flagstaff Hill', 'Allied Health', 'Counsellor', 'jesse.muller.85 @gmail.com ', -34.92865642, 138.5999107, 'N/A', true, true, false, true, false),
('Jess Bos', '- Under 18', 'Elizabeth', 'Allied Health', 'CAMHS Clinician/Social Worker', '1300 222 647', -34.92865642, 138.5999107, 'Child and Adolescent Mental Health Services', true, false, false, false, false),
('Jess Bos', '- Under 18', 'Adelaide', 'Allied Health', 'Non-binary, Gender Diversity Clinician  ', '8161 7227', -34.92865642, 138.5999107, 'Women''s and Children''s Hospital', true, false, false, false, false),
('Tracey Greaves', '- Under 18 - Over 18 - Low/no/NDIS cost options - GP referral may be required', 'Adelaide CBD', 'Allied Health', 'Mental Health Social Worker', '0410 512 665', -34.92865642, 138.5999107, 'Adelaide Trauma Centre', true, true, false, true, true),
('Daniel Hackett', '- Under 18 - Over 18 - Low/no/NDIS cost options', 'Mawson Lakes', 'Allied Health', ' Counsellor & Youth Worker ', '0422 759 172 ', -34.8434451, 138.701848, 'Harper Psychology and Counseling, Grand Junction Road, Hope Valley SA, Australia', true, true, false, true, false),
('Riki Owens-Bennett', 'Non-binary - Low/no/NDIS cost options', 'Adelaide', 'Allied Health', 'Community worker ', '8202 5190', -34.92865642, 138.5999107, 'Bfriend', false, false, false, true, false),
('Rachel Lafain', 'NDIS Support Coordinator - Low/no/NDIS cost options', '', 'Allied Health', 'Social Worker', '0404 679 135', -34.92865642, 138.5999107, 'Contemporary Coordination', false, false, false, true, false),
('Kirsty Degabriele', '- Low/no/NDIS cost options  University of South Australia UniSA Students Only', 'Adelaide', 'Allied Health', 'Mental Health Social Worker', 'Book via UniSA website', -34.92865642, 138.5999107, '', false, false, false, true, false),
('Rochelle Morgan', '- Low/no/NDIS cost options - Youth under 25', 'Adelaide', 'Allied Health', 'Social Worker ', '8255 3477', -34.92865642, 138.5999107, 'Metro Youth Health', false, false, false, true, false),
('Stacey Roy', '- Over 18', 'Adelaide', 'Allied Health', 'Mental Health Social Worker ', '7081 9331', -34.92865642, 138.5999107, 'Urban Wellness', false, true, false, false, false),
('Krystie Edwards', '', 'Adelaide CBD', 'Allied Health', 'Social Worker & Psychotherapist', '0413 654 555', -34.92865642, 138.5999107, 'Adelaide Trauma Centre', false, false, false, false, false),
('Sarah Short', 'Also online http://www.twcp.com.au - Under 18 - Over 18', 'Port Adelaide', 'Allied Health', 'Integrative Psychotherapist', '0434 160 086', -34.92865642, 138.5999107, '6 Lipson Street', true, true, false, false, false),
('Jude Hill', '- Under 18 - Over 18 - GP referral may be required', 'Adelaide', 'Allied Health', 'Mental Health Social Worker ', '7228 5363', -34.9383303, 138.6516452, 'Paediatric, Perinatal & Adult Therapy Centre, Tusmore Avenue, Tusmore SA, Australia', true, true, false, false, true),
('Varda Svigos', '- Over 18 - Youth under 25', 'Adelaide', 'Allied Health', 'Counsellor ', '7079 4647', -34.92865642, 138.5999107, 'Wisteria Bridge', false, true, false, false, false),
('Jess Bos', '- Under 18', 'Elizabeth', 'Allied Health', 'Non-binary, Gender Diversity Clinician, CAMHS Clinician/Social Worker ', '1300 222 647', -34.92865642, 138.5999107, 'Child and Adolescent Mental Health Services, Elizabeth', true, false, false, false, false),
('Jess Bos', '- Under 18', 'Adelaide', 'Allied Health', 'Non-binary, Gender Diversity Clinician, CAMHS Clinician/Social Worker ', '8161 7227', -34.92865642, 138.5999107, 'Women''s and Children''s Hospital', true, false, false, false, false),
('Joanne McNamara', '- Low/no/NDIS cost options', 'Adelaide', 'Allied Health', 'Student Counsellor (Social Worker) ', '8313 5663', -34.920603, 138.6062277, 'The University of Adelaide, Adelaide SA, Australia', false, false, false, true, false),
('Jacintha Power', '- Low/no/NDIS cost options', 'Adelaide', 'Allied Health', 'Student Counsellor (Social Worker) ', '8313 5663', -34.92865642, 138.5999107, 'University of Adelaide', false, false, false, true, false),
('Jodie Evans', '- Ages 21 and under', '', 'Allied Health', 'Psychotherapist  ', '7523 4547', -34.92865642, 138.5999107, 'Project 18', false, false, false, false, false),
('Dolly Amoroso', '', 'Mt Gambier', 'Allied Health', 'Social Worker and Sexologist ', '0423 329 472', -34.92865642, 138.5999107, 'Amorism', false, false, false, false, false),
('Catherine Leahy', '- Low/no/NDIS cost options', 'Adelaide', 'Allied Health', 'Student Counsellor (Social Worker) ', '8313 5663', -34.920603, 138.6062277, 'The University of Adelaide, Adelaide SA, Australia', false, false, false, true, false),
('April Morrison', '- Over 18', 'Adelaide', 'Allied Health', 'Counsellor and Psychotherapist', '7523 4586', -34.9186724, 138.5727875, '86 George Street, Thebarton SA, Australia', false, true, false, false, false),
('Dr Terry Evans', '- GP referral may be required ', 'Kensington Gardens', 'Clinical Psychologist', 'Clinical Psychologist', '407184656', 0, 0, 'Willow Tree Psychology & Wellbeing', false, false, false, false, true),
('Dr Terry Evans', '- GP referral may be required ', 'Stepney', 'Clinical Psychologist', 'Clinical Psychologist', '407184656', 0, 0, 'Stepney Psychology', false, false, false, false, true),
('Mallory Webber', 'Provisional Psychologist - GP referral may be required - Under 18 - Over 18 - Family', 'Torrensville', 'Clinical Psychologist', 'Clinical Psychologist', '8448 1106', 0, 0, 'Soothing Minds Counselling and Psychotherapy', true, true, false, false, true),
('Danica Gregory', '- GP referral may be required  - over 18   - experience supporting neurodiverse persons  - background in social psychology. ', 'St Peters', 'Clinical Psychologist', 'Clinical Psychologist', '(08) 7225 2172', 0, 0, 'Adelaide Psychology Partners 81 Payneham Road', false, false, false, false, true),
('Schae Matthews', '- GP referral may be required  - Open to under 18 patients  - Open to Youth Under 25', 'Gilles Plains', 'Clinical Psychologist', 'Clinical Psychologist', '1300 874 218', 0, 0, 'Taylored Psychology Suite 2/1 Sudholz Road', false, false, true, false, true),
('Dr Heather Mattner', '- GP referral may be required - Low/no/NDIS cost options', 'Stirling', 'Counselling Psychologist', 'Perinatal Health Psychologist ', '0414 499 544', 0, 0, '83 Mount Barker Road', false, false, false, true, true),
('Dr Heather Mattner', '- GP referral may be required - Low/no/NDIS cost options', 'Stirling', 'Counselling Psychologist', 'Perinatal Health Psychologist ', '0414 499 544', 0, 0, '83 Mount Barker Road', false, false, false, true, true),
('Kylie Agnew', '- GP referral may be required', 'North Adelaide', 'Counselling Psychologist', '', '0401 966 710', 0, 0, 'Youth Psychology SA', false, false, false, false, true),
('Jo-Anne Hamilton', '- GP referral may be required - Under 18 - Over 18 - Family', 'Norwood', 'Counselling Psychologist', '', '0419 849 017', 0, 0, '42 Beulah Road', true, true, false, false, true),
('Kylie Agnew', 'Alternative Education School - Must be a student here', 'Adelaide', 'Counselling Psychologist', '', '0451 828 080', 0, 0, 'Youth Inc. ', false, false, false, false, false),
('Sue Parkinson', '- GP referral may be required - Low/no/NDIS cost options', 'Mt Barker', 'Counselling Psychologist', 'Registered Psychologist', '0419 867 134', 0, 0, '17 Alexandrina Road', false, false, false, true, true),
('Rodney Cassel', '- GP referral may be required - Low/no/NDIS cost options - Under 18 - Youth Under 25', 'Gawler', 'Counselling Psychologist', 'Registered Psychologist', '8524 6683', 0, 0, 'Action Psychology SA', true, false, true, true, true),
('Amanda Bakker', '- GP referral may be required - Low/no/NDIS cost options', 'Torrens Park', 'Counselling Psychologist', 'Registered Psychologist', '0472 66 33 84', 0, 0, '154 Springbank Road', false, false, false, true, true),
('Dr Christian Highet', '- GP referral may be required - Under 18 - Over 18  Also practices at: <span>Psychmed Level 1 Bagot House 198 North Terrace Psychmed 1-3 Burman Avenue Psychmed 224 Seacombe Road Taylored Psychology Suite 2/1 Sudholz Road </span>  Option for clients to pay privately without a mental health care plan.', 'St Peters', 'Clinical Psychologist', 'Clinical Psychologist', '7225 2172', -34.9121222, 138.625241, 'Adelaide Psychology Partners, Payneham Road, St Peters SA, Australia', true, true, false, false, true),
('Dr Elsa Jureidini', '- Under 18 - low/no/NDIS cost options - GP referral may be required', 'Adelaide', 'Psychiatrist', 'Psychiatrist', '8161 7227', 0, 0, 'Women''s and Children''s Hospital', true, false, false, false, true),
('Dr Nazila Tai', '- GP referral may be required - low/no/NDIS cost options - Not taking new patients', 'Norwood', 'Psychiatrist', 'Psychiatrist', '8363 7222', 0, 0, 'Norwood Health on Fullarton', false, false, false, false, true),
('Dr Melanie Turner', '- Under 18 - GP referral may be required', 'Walkerville', 'Psychiatrist', 'Psychiatrist', '7231 1703', 0, 0, 'Child & Adolescent Psychiatry', true, false, false, false, true),
('Dr Georgina Cheng', '- GP referral may be required - Once off assessments', 'Norwood', 'Psychiatrist', 'Psychiatrist', '8331 1876', 0, 0, 'Barrett House', false, false, false, false, true),
('Dr Georgie Swift', '- Under 18 - low/no/NDIS Cost Options - GP referral may be required', 'Adelaide', 'Psychiatrist', 'Psychiatrist', '8161 7227', 0, 0, 'Women''s and Children''s Hospital', true, false, false, false, true),
('Dr Nikki Sommers', '', 'Newton', 'Other Specialists', 'Dental Surgeon', '8337 3878', -34.888249, 138.674579, 'Gentledentistry - Cosmetic & General Dentists, Montacute Road, Newton SA, Australia', false, false, false, false, false),
('Dr Corinne Maiolo', '', 'Mount Barker', 'Other Specialists', 'Dermatologist ', '8180 0659', 0, 0, 'myPRODERM', false, false, false, false, false),
('Dr Corinne Maiolo', '', 'Adelaide', 'Other Specialists', 'Dermatologist ', '8180 0659', 0, 0, 'myPRODERM', false, false, false, false, false),
('Dr Dennis Lau', '', 'Norwood', 'Other Specialists', 'Cardiologist ', '8313 9000', 0, 0, 'Cardiovascular Centre', false, false, false, false, false),
('Dr Jane Alderman', '', 'Stirling', 'General Practitioner', '', '8339 4344', 0, 0, 'Stirling Medical Clinic', false, false, false, false, false),
('Dr Matthew Teale', '- Low/no/NDIS cost options', 'Happy Valley', 'General Practitioner', '', '8322 2824', 0, 0, 'Fountain Valley Medical Centre', false, false, false, true, false),
('Dr Chek Ng', '- Low/no/NDIS cost options', 'Woodville South', 'General Practitioner', '', '8345 5341', 0, 0, 'Woodville South Medical Practice', false, false, false, true, false),
('Dr Stella Prescott', '', 'Tea Tree Gully', 'General Practitioner', '', '8396 2522', 0, 0, 'Pioneer Medical Centre', false, false, false, false, false),
('Dr Jemma Elliot', ' - Low/no/NDIS cost options - Not taking new patients', 'Adelaide', 'General Practitioner', '', '8410 0774', 0, 0, 'Adelaide Health Care', false, false, false, true, false),
('Dr Kasandra Melville', '- Low/no/NDIS cost options', 'Strathalbyn', 'General Practitioner', '', '8536 4466', 0, 0, 'Strathalbyn Family Medical Centre', false, false, false, true, false),
('Dr Kasandra Melville', '- Low/no/NDIS cost options', 'Hahndorf', 'General Practitioner', '', '8388 7066', 0, 0, 'Hahndorf Medical Centre', false, false, false, true, false),
('Dr Melanie George', '- Low/no/NDIS cost options', 'Happy Valley', 'General Practitioner', '', '8322 2824', 0, 0, 'Fountain Valley Medical Centre', false, false, false, true, false),
('Dr Dominique Baume', '- Low/no/NDIS cost options', 'Mawson Lakes', 'General Practitioner', '', '8359 6266', 0, 0, 'Mawson Lakes Health Care', false, false, false, true, false),
('Dr Nicole Mellor', '', 'Sefton Park', 'General Practitioner', '', '8269 1900', 0, 0, 'Regency Medical Clinic', false, false, false, false, false),
('Dr Anna Aisatullin', '- Low/no/NDIS cost options - Youth Under 25', 'Elizabeth', 'General Practitioner', '', '8255 3477', 0, 0, 'Metro Youth Health', false, false, true, true, false),
('Dr Emily Kilner', '', 'Glenelg', 'General Practitioner', '', '7228 5818', 0, 0, 'Pear Tree Family Practice', false, false, false, false, false),
('Dr Cicy Li', '', 'Parkside', 'General Practitioner', '', '8373 0888', 0, 0, 'Arkaba Medical Centre', false, false, false, false, false),
('Dr Natnalie Masli', '- Low/no/NDIS cost options', 'Adelaide', 'General Practitioner', '', '7099 5300', 0, 0, 'SHINE SA Hyde St Practice', false, false, false, true, false),
('Dr Darcie Barry-Keen', '- Low/no/NDIS cost options', 'Clare', 'General Practitioner', '', '8841 3777', -33.8327735, 138.6123172, 'Clare Medical Centre, Old North Road, Clare SA, Australia', false, false, false, true, false),
('Dr Adam Kowalczyk', '', 'O''Halloran Hill', 'General Practitioner', '', '08 7127 1566', -35.0688844, 138.5550344, 'O''Halloran Medical Centre, Main South Road, O''Halloran Hill SA, Australia', false, false, false, false, false);